sudo: required
dist: trusty
language: python
python:
  - "3.6"
install:
  - "pip install -U pip setuptools"
  - "pip install -U Cython"
  - "pip install https://github.com/dib-lab/pybbhash/archive/spacegraphcats.zip"
  - "pip install https://github.com/dib-lab/khmer/archive/master.zip"
  - "pip install git+https://github.com/dib-lab/sourmash@master#egg=sourmash"
  - "pip install https://github.com/spacegraphcats/spacegraphcats/archive/installable.zip"
  - "curl -L https://github.com/GATB/bcalm/releases/download/v2.2.0/bcalm-binaries-v2.2.0-Linux.tar.gz | tar -xzvf -"
  - "ls $PWD/bcalm-binaries-v2.2.0-Linux/bin/"
  - "export PATH=$PATH:$PWD/bcalm-binaries-v2.2.0-Linux/bin/"
  - "bcalm"
script:
  - spacegraphcats config.yaml extract_reads
